a = float(input("Enter first number: "))
b = float(input("Enter second number: "))
print("Addition:", a+b)
print("Subtraction:", a-b)
print("Multiplication:", a*b)
print("Division:", a/b)
print("Floor division:", a//b)
print("Exponential:", a**b)
print("Nanditha")
print("AIML")
